apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: my-replica-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-web
    # matchExpressions:
    #   - key: label-key
    #     operator: In
    #     values:
    #       - label-value1
    #       - label-value2      
  template:
    metadata:
      labels:
        app: nodejs-web
    spec:
      containers:
        - name: nodejs-web
          image: nodejs-web:1
